/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

import institutoabierto.modelo.Conexion;
import institutoabierto.modelo.Curso;
import institutoabierto.modelo.CursoData;
import institutoabierto.modelo.Persona;
import institutoabierto.modelo.PersonaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maqui's
 */
public class CursosTodosVistas extends javax.swing.JInternalFrame {

    /**
     * Creates new form CursosTodosVistas
     */
    private DefaultTableModel modelo;
//private ArrayList<Matricula> listaMatriculas;
private ArrayList<Curso> listaCursos;
//private MatriculaData matriculadata;
private CursoData cursoData;
//private PersonaData personadata;
//private ArrayList<Persona> listaPersonas;
private Conexion conexion;
    public CursosTodosVistas() {
        initComponents();
    try {
       conexion = new Conexion("jdbc:mysql://localhost/instituto_abierto","root","");
        modelo = new DefaultTableModel();
        
        cursoData = new CursoData (conexion);
        listaCursos= (ArrayList)cursoData.listaCursos();
        
        armaCabeceraTabla();
        cargaDatos();
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(AlumnosTodosVistas.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
public void armaCabeceraTabla(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("NOMBRE");
        columnas.add("DESCRIPCIÓN");
        columnas.add("COSTO");
        columnas.add("CUPO MÁXIMO");
        
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        tbCursos.setModel(modelo);
  }
public void cargaDatos(){
            
            CursoData md=new CursoData(conexion);
            listaCursos=(ArrayList) md.listaCursos();
        //Llenar filas
        for(Curso c:listaCursos){
        
            //Comparo por los id o sobreescribo el método equals en Materias
           // if(m.getMateria().getId()==mat.getId()){
            
            modelo.addRow(new Object[]{c.getId_curso(),c.getNombreCurso(),c.getDescripcion(),c.getCosto(),c.getCupoMax()});
            }           
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tbCursos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCursos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("LISTA DE CURSOS EN INSTITUTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCursos;
    // End of variables declaration//GEN-END:variables
}
