/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

import institutoabierto.modelo.Conexion;
import institutoabierto.modelo.Curso;
import institutoabierto.modelo.CursoData;
import institutoabierto.modelo.Matricula;
import institutoabierto.modelo.MatriculaData;
import institutoabierto.modelo.Persona;
import institutoabierto.modelo.PersonaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maqui's
 */
public class MatriculaxPersonaVistas extends javax.swing.JInternalFrame {

    
    private DefaultTableModel modelo;
private ArrayList<Matricula> listaMatriculas;
private ArrayList<Curso> listaCursos;

private CursoData cursodata;
private PersonaData personadata;
private ArrayList<Persona> listaPersonas;
private Conexion conexion;
private MatriculaData matriculadata;

private Curso curso;
    public MatriculaxPersonaVistas() {
     
        initComponents();
        try {
       
        conexion = new Conexion("jdbc:mysql://localhost/instituto_abierto","root","");
        modelo = new DefaultTableModel();
        
        matriculadata=new MatriculaData(conexion);
        listaMatriculas= (ArrayList)matriculadata.listaMatriculas();
        
        cursodata = new CursoData(conexion);
        listaCursos=(ArrayList)cursodata.listaCursos();
        
        personadata = new PersonaData (conexion);
        listaPersonas= (ArrayList)personadata.listaPersonas();
        
        cargaPersonas();
        armaCabeceraTabla();
        cargaDatos();
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(MatriculaxPersonaVistas.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
public void armaCabeceraTabla(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("FECHA");
        columnas.add("COSTO");
        columnas.add("CURSO");
        //columnas.add("ID_PERSONA");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        TbMatricula.setModel(modelo);
  }
public void borraFilasTabla(){

            int a =modelo.getRowCount()-1;
            System.out.println("Tabla "+a);
            for(int i=a;i>=0;i--){
                modelo.removeRow(i );
                System.out.println("Tabla "+i);
            }
      }
 public void cargaDatos(){
            //borraFilasTabla();
                       
         //Obtengo la Materia q esta seleccionada en el ComboBox
            MatriculaData md=new MatriculaData(conexion);
             Persona seleccionada=(Persona)CbPersonas.getSelectedItem();
           listaMatriculas=(ArrayList) md.obtenerMatriculaxPersona(seleccionada.getId_persona());
        //Llenar filas
        for(Matricula m:listaMatriculas){
        
            //Comparo por los id o sobreescribo el método equals en Materias
           // if(m.getMateria().getId()==mat.getId()){
            
            modelo.addRow(new Object[]{m.getId_matricula(),m.getFecha(),m.getCosto(),m.getCurso().getNombreCurso()});
            }           
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TbMatricula = new javax.swing.JTable();
        CbPersonas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TbMatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TbMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbMatricula);

        CbPersonas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPersonasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("LISTA DE MATRÍCULAS POR PERSONA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(CbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(CbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPersonasActionPerformed
borraFilasTabla();
cargaDatos();// TODO add your handling code here:
    }//GEN-LAST:event_CbPersonasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Persona> CbPersonas;
    private javax.swing.JTable TbMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public void cargaPersonas(){

   
    for(Persona item:listaPersonas){
            CbPersonas.addItem(item);
    }

}
}
