/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

import institutoabierto.modelo.Conexion;
import institutoabierto.modelo.Curso;
import institutoabierto.modelo.CursoData;
import institutoabierto.modelo.Matricula;
import institutoabierto.modelo.MatriculaData;
import institutoabierto.modelo.Persona;
import institutoabierto.modelo.PersonaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maqui's
 */
public class MatriculasTodasVistas extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
private ArrayList<Matricula> listaMatriculas;
//private ArrayList<Curso> listaCursos;
private MatriculaData matriculadata;
//private CursoData cursoData;
//private PersonaData personadata;
//private ArrayList<Persona> listaPersonas;
private Conexion conexion;
    /**
     * Creates new form MatriculasTodasVistas
     */
    public MatriculasTodasVistas() {
     initComponents();
        try {
       
        conexion = new Conexion("jdbc:mysql://localhost/instituto_abierto","root","");
        modelo = new DefaultTableModel();
        
        matriculadata=new MatriculaData(conexion);
        listaMatriculas= (ArrayList)matriculadata.listaMatriculas();
        
        armaCabeceraTabla();
        cargaDatos();
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(MatriculasTodasVistas.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
public void armaCabeceraTabla(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("FECHA");
        columnas.add("COSTO");
        columnas.add("CURSO");
        columnas.add("PERSONA");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        TbMatriculas.setModel(modelo);
  }
public void cargaDatos(){
            //borraFilasTabla();
                       
         //Obtengo la Materia q esta seleccionada en el ComboBox
            MatriculaData md=new MatriculaData(conexion);
            listaMatriculas=(ArrayList) md.listaMatriculas();
        //Llenar filas
        for(Matricula m:listaMatriculas){
        
            //Comparo por los id o sobreescribo el método equals en Materias
           // if(m.getMateria().getId()==mat.getId()){
            
            modelo.addRow(new Object[]{m.getId_matricula(),m.getFecha(),m.getCosto(),m.getCurso().getNombreCurso(),m.getPersona().getNombrePersona()});
            }           
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TbMatriculas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TbMatriculas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TbMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbMatriculas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("LISTA MATRÍCULAS EN INSTITUTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbMatriculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
