/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

import javax.swing.JFrame;

/**
 *
 * @author Maqui's
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        ItSalir = new javax.swing.JMenuItem();
        MnCursos = new javax.swing.JMenu();
        ItFormulCursos = new javax.swing.JMenuItem();
        MnUsuarios = new javax.swing.JMenu();
        ItFormulUsuar = new javax.swing.JMenuItem();
        MnInscripciones = new javax.swing.JMenu();
        ItInsertInscrip = new javax.swing.JMenuItem();
        MnConsultas = new javax.swing.JMenu();
        ItListadoAlumnos = new javax.swing.JMenuItem();
        ItMatriculaxPer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ItInfoGral = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        itCursosTodos = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(102, 255, 102));
        escritorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        escritorio.setForeground(new java.awt.Color(153, 255, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/institutoabierto/vistas/imagenes/einstein21.gif"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/institutoabierto/vistas/imagenes/titulo instituto.png"))); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );

        MnArchivo.setText("Archivo");
        MnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnArchivoActionPerformed(evt);
            }
        });

        ItSalir.setText("Salir");
        ItSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItSalirActionPerformed(evt);
            }
        });
        MnArchivo.add(ItSalir);

        jMenuBar1.add(MnArchivo);

        MnCursos.setText("Profesores");
        MnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCursosActionPerformed(evt);
            }
        });

        ItFormulCursos.setText("Gestión cursos");
        ItFormulCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItFormulCursosActionPerformed(evt);
            }
        });
        MnCursos.add(ItFormulCursos);

        jMenuBar1.add(MnCursos);

        MnUsuarios.setText("Usuarios");
        MnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUsuariosActionPerformed(evt);
            }
        });

        ItFormulUsuar.setText("Formulario de usuarios");
        ItFormulUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItFormulUsuarActionPerformed(evt);
            }
        });
        MnUsuarios.add(ItFormulUsuar);

        jMenuBar1.add(MnUsuarios);

        MnInscripciones.setText("Matricula ");

        ItInsertInscrip.setText("Alta/Baja a curso");
        ItInsertInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItInsertInscripActionPerformed(evt);
            }
        });
        MnInscripciones.add(ItInsertInscrip);

        jMenuBar1.add(MnInscripciones);

        MnConsultas.setText("Consultas");
        MnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConsultasActionPerformed(evt);
            }
        });

        ItListadoAlumnos.setText("Listado de alumnos por curso");
        ItListadoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItListadoAlumnosActionPerformed(evt);
            }
        });
        MnConsultas.add(ItListadoAlumnos);

        ItMatriculaxPer.setText("Matriculas por persona");
        ItMatriculaxPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItMatriculaxPerActionPerformed(evt);
            }
        });
        MnConsultas.add(ItMatriculaxPer);

        jMenuBar1.add(MnConsultas);

        jMenu4.setText("Información");

        ItInfoGral.setText("Lista de Matriculas");
        ItInfoGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItInfoGralActionPerformed(evt);
            }
        });
        jMenu4.add(ItInfoGral);

        jMenuItem3.setText("Lista de Alumnos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        itCursosTodos.setText("Lista de Cursos");
        itCursosTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCursosTodosActionPerformed(evt);
            }
        });
        jMenu4.add(itCursosTodos);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //INSTANCIA AL ESCRITORIO
   
    private void MnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUsuariosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        PersonasVistas pv= new PersonasVistas();
        pv.setVisible(true);
        escritorio.add(pv);
        escritorio.moveToFront(pv);
    }//GEN-LAST:event_MnUsuariosActionPerformed

    //OPCIÓN PARA INGRESAR A FORMULARIO DE PERSONAS
    private void ItFormulUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItFormulUsuarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        PersonasVistas pv= new PersonasVistas();
        pv.setVisible(true);
        escritorio.add(pv);
        escritorio.moveToFront(pv);
  
    }//GEN-LAST:event_ItFormulUsuarActionPerformed

    private void MnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnConsultasActionPerformed
//OPCIÓN PARA INGRESAR A LISTADO DE ALUMNOS POR CURSO
    private void ItListadoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItListadoAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        AlumnosCursosVistas acv= new AlumnosCursosVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItListadoAlumnosActionPerformed

    private void MnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCursosActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_MnCursosActionPerformed

    private void ItFormulCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItFormulCursosActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        
       CursoVistas acv= new CursoVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItFormulCursosActionPerformed

    private void ItInsertInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItInsertInscripActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
       MatriculaVistas acv= new MatriculaVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItInsertInscripActionPerformed

    private void MnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnArchivoActionPerformed

    private void ItSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItSalirActionPerformed

    private void ItMatriculaxPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItMatriculaxPerActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
       MatriculaxPersonaVistas acv= new MatriculaxPersonaVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItMatriculaxPerActionPerformed

    private void ItInfoGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItInfoGralActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();

        MatriculasTodasVistas acv= new MatriculasTodasVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItInfoGralActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();

        AlumnosTodosVistas acv= new AlumnosTodosVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void itCursosTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCursosTodosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();

        CursosTodosVistas acv= new CursosTodosVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_itCursosTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItFormulCursos;
    private javax.swing.JMenuItem ItFormulUsuar;
    private javax.swing.JMenuItem ItInfoGral;
    private javax.swing.JMenuItem ItInsertInscrip;
    private javax.swing.JMenuItem ItListadoAlumnos;
    private javax.swing.JMenuItem ItMatriculaxPer;
    private javax.swing.JMenuItem ItSalir;
    private javax.swing.JMenu MnArchivo;
    private javax.swing.JMenu MnConsultas;
    private javax.swing.JMenu MnCursos;
    private javax.swing.JMenu MnInscripciones;
    private javax.swing.JMenu MnUsuarios;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itCursosTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
