/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

import institutoabierto.modelo.Conexion;
import institutoabierto.modelo.Curso;
import institutoabierto.modelo.CursoData;
import institutoabierto.modelo.Persona;
import institutoabierto.modelo.PersonaData;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Maqui's
 */
public class CursoVistas extends javax.swing.JInternalFrame {
 private Conexion conexion;
 private CursoData cursodata;
 private PersonaData personadata;
    /**
     * Creates new form CursoVistas
     */
    public CursoVistas() {
      initComponents(); 
      
      try {
         
         conexion = new Conexion("jdbc:mysql://localhost/instituto_abierto", "root", "");
         cursodata = new CursoData(conexion);
         personadata = new PersonaData(conexion);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(CursoVistas.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texNombre = new javax.swing.JTextField();
        texCosto = new javax.swing.JTextField();
        texCupoMax = new javax.swing.JTextField();
        texdni = new javax.swing.JTextField();
        btguardarcurso = new javax.swing.JButton();
        texidcurso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtBuscar = new javax.swing.JButton();
        BtBorrar = new javax.swing.JButton();
        btactualizar = new javax.swing.JButton();
        BtLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texDescripcion = new javax.swing.JTextArea();

        jTextField4.setText("jTextField4");

        titulo.setText("CURSOS");

        texNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNombreActionPerformed(evt);
            }
        });

        texCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texCostoActionPerformed(evt);
            }
        });

        btguardarcurso.setText("Guardar");
        btguardarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarcursoActionPerformed(evt);
            }
        });

        texidcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidcursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre curso");

        jLabel3.setText("Descripción");

        jLabel4.setText("Costo");

        jLabel5.setText("Cupo Máximo");

        jLabel6.setText("ID Responsable");

        jLabel7.setText("ID Curso");

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        BtBorrar.setText("Borrar");
        BtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrarActionPerformed(evt);
            }
        });

        btactualizar.setText("Actualizar");
        btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarActionPerformed(evt);
            }
        });

        BtLimpiar.setText("Limpiar");
        BtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimpiarActionPerformed(evt);
            }
        });

        texDescripcion.setColumns(20);
        texDescripcion.setRows(5);
        jScrollPane1.setViewportView(texDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(titulo)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(BtBorrar)
                                .addGap(69, 69, 69)
                                .addComponent(btactualizar)
                                .addGap(65, 65, 65)
                                .addComponent(BtLimpiar)
                                .addContainerGap(34, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtBuscar)
                                .addGap(74, 74, 74))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(btguardarcurso)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(texdni, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texCupoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texNombre)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(texidcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(202, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BtBuscar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(texCosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(texCupoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(texdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(texidcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btguardarcurso)
                    .addComponent(BtBorrar)
                    .addComponent(btactualizar)
                    .addComponent(BtLimpiar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texNombreActionPerformed
//OPCION PARA GUARDAR UN CURSO
    private void btguardarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarcursoActionPerformed
        // TODO add your handling code here:
        String nombreCurso = texNombre.getText();
        String descripcion = texDescripcion.getText();
        double costo = Double.parseDouble(texCosto.getText());
        int cupoMax = Integer.parseInt(texCupoMax.getText());
        Persona persona = personadata.buscarPersona(Integer.parseInt(texdni.getText()));
        System.out.println(persona);
        
        Curso curso = new Curso (nombreCurso, descripcion, costo, cupoMax, persona);
        cursodata.resgitrarCurso(curso);
        texidcurso.setText(curso.getId_curso()+"");
    }//GEN-LAST:event_btguardarcursoActionPerformed

    private void texCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texCostoActionPerformed

    private void texidcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidcursoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_texidcursoActionPerformed
//OPCIÓN PARA GUARDAR UN CURSO
    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
      String nombreCurso=(texNombre.getText());
        Curso curso = cursodata.buscarCurso(nombreCurso);
        if (curso!=null){
          texNombre.setText(curso.getNombreCurso());
          texDescripcion.setText(curso.getDescripcion());
          texCosto.setText(curso.getCosto()+""); 
          texCupoMax.setText(curso.getCupoMax()+"");
          texdni.setText(curso.getPersona().getId_persona()+"");
          texidcurso.setText(curso.getId_curso()+"");
// TODO add your handling code here:
        }
    }//GEN-LAST:event_BtBuscarActionPerformed
   //OPCIÓN PARA BORRAR UN CURSO
    private void BtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrarActionPerformed
       int id_curso=Integer.parseInt(texidcurso.getText());
       cursodata.borrarCurso(id_curso);   // TODO add your handling code here:
    }//GEN-LAST:event_BtBorrarActionPerformed
//OPCIÓN PARA ACTUALIZAR UN CURSO (ID PERSONA PONE -1)
    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
        // TODO add your handling code here:
        if(texidcurso.getText()!=null){
        
        int id_curso=Integer.parseInt(texidcurso.getText());
        String nombreCurso = texNombre.getText();
        String descripcion = texDescripcion.getText();
        double costo = Double.parseDouble(texCosto.getText());
        int cupoMax = Integer.parseInt(texCupoMax.getText());
        
        //Persona persona = new Persona();
        //persona.getId_persona();
       //personadata.buscarPersonaxId(persona.getId_persona());
          
        Curso curso = new Curso(id_curso, nombreCurso, descripcion, costo, cupoMax);
        cursodata.actualizarCurso(curso);
        }
    }//GEN-LAST:event_btactualizarActionPerformed
//OPCION PARA BORRAR TODOS LOS CAMPOS DEL FORMULARIO
    private void BtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimpiarActionPerformed
     texCosto.setText("");
     texCupoMax.setText("");
     texDescripcion.setText("");
     texNombre.setText(""); 
     texdni.setText("");
     texidcurso.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_BtLimpiarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBorrar;
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtLimpiar;
    private javax.swing.JButton btactualizar;
    private javax.swing.JButton btguardarcurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField texCosto;
    private javax.swing.JTextField texCupoMax;
    private javax.swing.JTextArea texDescripcion;
    private javax.swing.JTextField texNombre;
    private javax.swing.JTextField texdni;
    private javax.swing.JTextField texidcurso;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
