/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

import institutoabierto.modelo.Conexion;
import institutoabierto.modelo.Curso;
import institutoabierto.modelo.CursoData;
import institutoabierto.modelo.Matricula;
import institutoabierto.modelo.MatriculaData;
import institutoabierto.modelo.Persona;
import institutoabierto.modelo.PersonaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maqui's
 */
public class MatriculaVistas extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
private ArrayList<Matricula> listaMatriculas;
private ArrayList<Curso> listaCursos;
private MatriculaData matriculaData;
private CursoData cursoData;
private PersonaData personaData;
private ArrayList<Persona> listaPersonas;
private Conexion conexion;
private MatriculaData matriculadata;
private PersonaData personadata;
private Curso curso;
    /**
     * Creates new form MatriculaVistas
     */
    public MatriculaVistas() {
    try {
        initComponents();
        conexion = new Conexion("jdbc:mysql://localhost/instituto_abierto","root","");
        modelo = new DefaultTableModel();
        
        matriculaData=new MatriculaData(conexion);
        listaMatriculas= (ArrayList)matriculaData.listaMatriculas();
        
        cursoData = new CursoData(conexion);
        listaCursos=(ArrayList)cursoData.obtenerCursos();
        
        personaData = new PersonaData (conexion);
        listaPersonas= (ArrayList)personaData.obtenerPersonas();
        
        cargarCursos();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(MatriculaVistas.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxIdMat = new javax.swing.JTextField();
        TxCosto = new javax.swing.JTextField();
        TxDni = new javax.swing.JTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        Btguardar = new javax.swing.JButton();
        BtBorrar = new javax.swing.JButton();
        Btactualizar = new javax.swing.JButton();
        Btlimpar = new javax.swing.JButton();
        JcbListaCursos = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MATRICULA");

        jLabel2.setText("ID Matricula");

        jLabel3.setText("Fecha inscripción");

        jLabel4.setText("Costo matricula");

        jLabel5.setText("Dni alumno");

        jLabel6.setText("Cursos");

        Btguardar.setText("Guardar");
        Btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtguardarActionPerformed(evt);
            }
        });

        BtBorrar.setText("Borrar");
        BtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrarActionPerformed(evt);
            }
        });

        Btactualizar.setText("Actualizar");

        Btlimpar.setText("Limpiar");

        JcbListaCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbListaCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Btguardar)
                        .addGap(31, 31, 31)
                        .addComponent(BtBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(Btactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(Btlimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxIdMat)
                            .addComponent(TxDni)
                            .addComponent(TxCosto)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(JcbListaCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TxIdMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JcbListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btguardar)
                    .addComponent(BtBorrar)
                    .addComponent(Btactualizar)
                    .addComponent(Btlimpar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrarActionPerformed
        /* TODO add your handling code here:
        int id_matricula=Integer.parseInt(TxIdMat.getText());
        matriculadata.borrarMatricula(int id_persona,int id_curso); 

    }//GEN-LAST:event_BtBorrarActionPerformed

    private void BtguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtguardarActionPerformed
        // TODO add your handling code here:
        Persona persona = personadata.buscarPersonaxId(Integer.parseInt(TxDni.getText()));
        Curso curso = cursodata.buscarCurso(TxNombreCurso.getText());
    }//GEN-LAST:event_BtguardarActionPerformed
*/
        }
    private void JcbListaCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbListaCursosActionPerformed
        // TODO add your handling code here:
        
          

    }//GEN-LAST:event_JcbListaCursosActionPerformed
    
 //ME CARGA LOS CURSOS QUE TENGO EN LA LISTA
public void cargarCursos (){
    
    for(Curso item:listaCursos){
        JcbListaCursos.addItem(item);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBorrar;
    private javax.swing.JButton Btactualizar;
    private javax.swing.JButton Btguardar;
    private javax.swing.JButton Btlimpar;
    private javax.swing.JComboBox<Curso> JcbListaCursos;
    private javax.swing.JTextField TxCosto;
    private javax.swing.JTextField TxDni;
    private javax.swing.JTextField TxIdMat;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
