/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutoabierto.vista;

/**
 *
 * @author Maqui's
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        ItSalir = new javax.swing.JMenuItem();
        MnCursos = new javax.swing.JMenu();
        ItFormulCursos = new javax.swing.JMenuItem();
        MnUsuarios = new javax.swing.JMenu();
        ItFormulUsuar = new javax.swing.JMenuItem();
        MnInscripciones = new javax.swing.JMenu();
        ItInsertInscrip = new javax.swing.JMenuItem();
        MnConsultas = new javax.swing.JMenu();
        ItListadoAlumnos = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 153, 153));
        escritorio.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        MnArchivo.setText("Archivo");

        ItSalir.setText("Salir");
        MnArchivo.add(ItSalir);

        jMenuBar1.add(MnArchivo);

        MnCursos.setText("Profesores");
        MnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCursosActionPerformed(evt);
            }
        });

        ItFormulCursos.setText("Crear nuevo curso");
        ItFormulCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItFormulCursosActionPerformed(evt);
            }
        });
        MnCursos.add(ItFormulCursos);

        jMenuBar1.add(MnCursos);

        MnUsuarios.setText("Alumnos");
        MnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUsuariosActionPerformed(evt);
            }
        });

        ItFormulUsuar.setText("Inscipción general");
        ItFormulUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItFormulUsuarActionPerformed(evt);
            }
        });
        MnUsuarios.add(ItFormulUsuar);

        jMenuBar1.add(MnUsuarios);

        MnInscripciones.setText("Matricula ");

        ItInsertInscrip.setText("Inscripción a curso");
        ItInsertInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItInsertInscripActionPerformed(evt);
            }
        });
        MnInscripciones.add(ItInsertInscrip);

        jMenuBar1.add(MnInscripciones);

        MnConsultas.setText("Consultas");
        MnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConsultasActionPerformed(evt);
            }
        });

        ItListadoAlumnos.setText("Listado de alumnos por curso");
        ItListadoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItListadoAlumnosActionPerformed(evt);
            }
        });
        MnConsultas.add(ItListadoAlumnos);

        jMenuBar1.add(MnConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //INSTANCIA AL ESCRITORIO
    private void MnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUsuariosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        PersonasVistas pv= new PersonasVistas();
        pv.setVisible(true);
        escritorio.add(pv);
        escritorio.moveToFront(pv);
    }//GEN-LAST:event_MnUsuariosActionPerformed

    //OPCIÓN PARA INGRESAR A FORMULARIO DE PERSONAS
    private void ItFormulUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItFormulUsuarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        PersonasVistas pv= new PersonasVistas();
        pv.setVisible(true);
        escritorio.add(pv);
        escritorio.moveToFront(pv);
  
    }//GEN-LAST:event_ItFormulUsuarActionPerformed

    private void MnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnConsultasActionPerformed
//OPCIÓN PARA INGRESAR A LISTADO DE ALUMNOS POR CURSO
    private void ItListadoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItListadoAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        AlumnosCursosVistas acv= new AlumnosCursosVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItListadoAlumnosActionPerformed

    private void MnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCursosActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_MnCursosActionPerformed

    private void ItFormulCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItFormulCursosActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        
       CursoVistas acv= new CursoVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItFormulCursosActionPerformed

    private void ItInsertInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItInsertInscripActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
       MatriculaVistas acv= new MatriculaVistas();
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
    }//GEN-LAST:event_ItInsertInscripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItFormulCursos;
    private javax.swing.JMenuItem ItFormulUsuar;
    private javax.swing.JMenuItem ItInsertInscrip;
    private javax.swing.JMenuItem ItListadoAlumnos;
    private javax.swing.JMenuItem ItSalir;
    private javax.swing.JMenu MnArchivo;
    private javax.swing.JMenu MnConsultas;
    private javax.swing.JMenu MnCursos;
    private javax.swing.JMenu MnInscripciones;
    private javax.swing.JMenu MnUsuarios;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
